different warning syntax, no set status

diff --git a/.github/workflows/axe-a11y-check.yml b/.github/workflows/axe-a11y-check.yml
--- a/.github/workflows/axe-a11y-check.yml
+++ b/.github/workflows/axe-a11y-check.yml
@@ -33,8 +33,8 @@ jobs:
         run: |
           npm install -g @axe-core/cli
           sleep 90
-          axe http://127.0.0.1:8080 --chromedriver-path $(npm root -g)/chromedriver/bin/chromedriver --exit || echo "::set-output name=status::warning"
+          axe http://127.0.0.1:8080 --chromedriver-path $(npm root -g)/chromedriver/bin/chromedriver --exit || echo "status=warning" >> $GITHUB_ENV
       
       - name: Set output status to warning (if test fails)
-        if: steps.axe-test.outputs.status == 'warning'
-        run: echo "::warning Accessibility tests failed, but this does not block (most) PRs."
+        if: env.status == 'warning'
+        run: echo "::warning::Accessibility tests failed, but this does not block (most) PRs."
